config/routes.rb
Ipasa::Application.routes.draw do
  devise_for :users

  root :to => 'pages#home'
  resources :profiles
  resources :types
  resources :rents
  resources :lease_structures       
  resources :rent_documents
  resources :invoices
  resources :surcharges
  resources :documents  
  resources :duties  
  resources :leases
  resources :localities
  resources :properties
  resources :messages
  resources :pages
  
  namespace :admin do
    root :to => 'base#index'
      match "propiedades" , :to => "properties#tab"
      match "perfiles", :to => "profiles#tab"
      match "localidades", :to => "localities#tab"
      match "servicios", :to => "services#tab"
      match "tiposinmueble", :to => "types#tab"
      match "arrendamientos",:to => "leases#tab"
      match "Videos",:to=> "videos#tab"
      resources :properties
      resources :profiles
      resources :leases
      resources :localities
      resources :services
      resources :types
      resources :videos
  end
  match 'message'   => 'messages#new', :as => 'message', :via => :get
  match 'message'   => 'messages#create', :as => 'message', :via => :post
  
  

end

app/controllers/admin/leases_controller.rb
class Admin::LeasesController < Admin::ResourceController
  def index
    @leases = Lease.find(:all)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leases } 
      format.js
    end
  end

  def show
    @lease = Lease.find(params[:id])
    @title="Informacion de arrendamiento"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lease }
      format.js
    end
  end

  def new
    @lease = Lease.new
    @titulo="Nuevo arrendamiento"
    @properties=Property.all
    @types=Type.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lease }
      format.js
    end
  end

  def edit
    @lease = Lease.find(params[:id])
     @titulo = "Actualizar arrendamiento"
    respond_to do |format|
      format.html
      format.json { render json: @lease }
      format.js
    end
  end

  def create
    @lease = Lease.new(params[:lease])
    respond_to do |format|
      if @lease.save
        format.html { redirect_to action:"tab" }
        format.json { render json: @lease, status: :created, location: @lease }
      else
        format.html { render action: "new" }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @lease = Lease.find(params[:id])
    respond_to do |format|
      if @lease.update_attributes(params[:lease])
        format.html { redirect_to action:"tab" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lease = Lease.find(params[:id])
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to action:"tab" }
      format.json { head :no_content }
    end
  end

  def tab
    @leases = Lease.all
     respond_to do |format|
      format.html
    end
  end

end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  def index
    @leases = Lease.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leases }
    end
  end

  def show
    @lease = Lease.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lease }
    end
  end

  def new
    @lease = Lease.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lease }
    end
  end

  def edit
    @lease = Lease.find(params[:id])
  end

  def create
    @lease = Lease.new(params[:lease])
    respond_to do |format|
      if @lease.save
        format.html { redirect_to @lease, notice: 'Lease was successfully created.' }
        format.json { render json: @lease, status: :created, location: @lease }
      else
        format.html { render action: "new" }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @lease = Lease.find(params[:id])
    respond_to do |format|
      if @lease.update_attributes(params[:lease])
        format.html { redirect_to @lease, notice: 'Lease was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lease = Lease.find(params[:id])
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to leases_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/leases/_form.html.erb
<h1><%= @titulo %></h1>
<%= simple_form_for [:admin, @lease], :html => { :class => 'form-horizontal' } do |f| %>
    <%= f.association :profile %>
    <%= f.input :num_int %>
    <%= f.input :status_renta, :as => :boolean,:label=>"¿Se encuentra ocupado?" %>
    <%= f.input :precio %>
    <%= f.input :descripcion %>
    <%= f.submit %>
<% end %>

app/views/admin/leases/edit.js.erb
$(document).ready(function() {
	$('.modal-body').empty();	
	$('.modal-body').html("<%= escape_javascript render :partial => 'form' %>");                   
});

app/views/admin/leases/index.html.erb
<h1><%= @titulo %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Número interno</th>
      <th>Estado</th>
      <th>Precio</th>
      <th>Descripción</th>
      <th>Perfil de Inmueble</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
  <% @leases.each do |lease| %>
    <tr>
      <td><%= lease.num_int %></td>
      <td><%= lease.en_renta? %></td>
      <td><%= lease.precio %></td>
      <td><p class="description"><%= lease.descripcion %></p></td>
      <td><%= lease.profile.nombre %></td>
      <td>
        <%= link_to_show(admin_lease_path(lease)) %>
        <%= link_to_edit(admin_lease_path(lease)) %>
        <%= link_to_delete(admin_lease_path(lease)) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/leases/index.js.erb
$(document).ready(function() {
    $('#content').html("<%= escape_javascript render(:file => 'admin/leases/index', :formats => [:html])  %>");
});

app/views/admin/leases/show.html.erb
<div class="page-header">
  <h1>Numero:#<%= @lease.num_int %></h1>
</div>

<div class="well">
	<dl class="dl-horizontal">
		<dd><%= @lease.num_int %></dd>
	    <dd><%= @lease.en_renta? %></dd>
	    <dd><%= @lease.precio %></dd>
	    <dd><%= @lease.descripcion %></dd>
	</dl>
</div>

app/views/admin/leases/show.js.erb
$(document).ready(function() {
$('.modal-body').empty();
$('.modal-body').html("<%= escape_javascript render(:file => 'admin/leases/show', :formats => [:html])  %>");    
});

app/views/admin/leases/tab.html.erb
<ul class="nav nav-tabs">
	<li class="active"><%= link_to_index_tab("leases")%></li>
	<li><%= link_to_new_tab("leases")%></li>
</ul>
<div id="content" class="tab-pane active">
	<%= render(:file => 'admin/leases/index') %>
</div>
 