config/routes.rb
Ipasa::Application.routes.draw do
  devise_for :users

  root :to => 'pages#home'
  resources :profiles
  resources :types
  resources :rents
  resources :lease_structures       
  resources :rent_documents
  resources :invoices
  resources :surcharges
  resources :documents  
  resources :duties  
  resources :leases
  resources :localities
  resources :properties
  resources :messages
  resources :pages
  
  namespace :admin do
    root :to => 'base#index'
      match "propiedades" , :to => "properties#tab"
      match "perfiles", :to => "profiles#tab"
      match "localidades", :to => "localities#tab"
      match "servicios", :to => "services#tab"
      match "tiposinmueble", :to => "types#tab"
      match "arrendamientos",:to => "leases#tab"
      match "Videos",:to=> "videos#tab"
      resources :properties
      resources :profiles
      resources :leases
      resources :localities
      resources :services
      resources :types
      resources :videos
  end
  match 'message'   => 'messages#new', :as => 'message', :via => :get
  match 'message'   => 'messages#create', :as => 'message', :via => :post
  
  

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :nombre
  has_many :rent_documents
  has_many :rents , through: :rent_documents
end

app/models/duty.rb
class Duty < ActiveRecord::Base
  attr_accessible :fecha, :monto, :property_id
  belongs_to :property
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :image_content_type, :image_description, :image_file_name, :image_file_size, :video_id , :image
  belongs_to :video
  has_attached_file :image , :styles => {:large => "650x400" , :thumb => "80x80>"  } , 
  :path => ":rails_root/public/images/videos/:id/:style/:basename.:extension",
  :url => "/images/videos/:id/:style/:basename.:extension"
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :fecha_vencimiento, :folio, :monto, :rent_id
  belongs_to :rent
  has_many :surcharges
  
end

app/models/lease.rb
class Lease < ActiveRecord::Base
  attr_accessible :descripcion, :num_int, :precio, :status_renta, :user_id, :profile_id
  belongs_to :profile 

  def en_renta?
  	self.status_renta ? 'Ocupado' : 'Disponible' 
  end
end

app/models/locality.rb
class Locality < ActiveRecord::Base
  attr_accessible :name
  has_many :properties, :dependent => :destroy
  validates :name, presence: true
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :nombre, :email, :asunto, :mensaje
  validates :nombre, :email, :asunto, :mensaje, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def initialize(attributes = {})
    attributes.each do |nombre, value|
      send("#{nombre}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
attr_accessible :photo_content_type, :photo_descripcion, :photo_file_name, :photo_file_size, :profile_id , :photo
belongs_to :profile
has_attached_file :photo , :styles => {:large => "650x400" , :thumb => "80x80>"  } , 
  :path => ":rails_root/public/images/inmuebles/:id/:style/:basename.:extension",
  :url => "/images/inmuebles/:id/:style/:basename.:extension"
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :picture_content_type, :picture_file_name, :picture_file_size, :picture_upload_date, :property_id ,  :picture_descripcion , :picture 
  belongs_to :property			
  has_attached_file :picture , :styles => {:large => "650x400" , :thumb => "80x80>"  } , 
  :path => ":rails_root/public/images/propiedades/:id/:style/:basename.:extension",
  :url => "/images/propiedades/:id/:style/:basename.:extension"
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :descripcion, :nombre, :type_id , :property_id , :photos_attributes , :banos , :recamaras ,:sala ,:cocina , :cuarto
  belongs_to :property
  belongs_to :type
  has_many :leases , :dependent => :destroy
  #paperclip
  has_many :photos , :dependent => :destroy
  accepts_nested_attributes_for :photos , 
  :reject_if => lambda { |a| a[:photo_descripcion].blank? } , 
  :allow_destroy => true
end

app/models/property.rb
class Property < ActiveRecord::Base	
  attr_accessible :description, :address, :google_maps, :locality_id, :name, :user_id, :catastral_reference, :pictures_attributes, :services_attributes 
  belongs_to :locality
  belongs_to :user
  has_many :duties
  has_many :videos
  has_many :leases 
  has_many :profiles , :dependent => :destroy

  has_many :services , :dependent  => :destroy
  accepts_nested_attributes_for :services , 
  :reject_if => lambda { |a| a[:nombre].blank? }, 
  :allow_destroy => true

  has_many :pictures , :dependent => :destroy
  accepts_nested_attributes_for :pictures , 
  :reject_if => lambda { |a| a[:picture_descripcion].blank? }, 
  :allow_destroy => true

  validates :locality_id,:name, :address, :google_maps,
    :description, :catastral_reference, presence: true

  def google_iframe
    "#{self.google_maps}&amp;output=embed"
  end
end

app/models/rent.rb
class Rent < ActiveRecord::Base
  attr_accessible :descuento, :fecha_fin, :fecha_inicio, :property_user_id
  has_many :rent_documents
  has_many :documents , through: :rent_documents
  has_many :invoices
  belongs_to :lease_user
end

app/models/rent_document.rb
class RentDocument < ActiveRecord::Base
  attr_accessible :document_id, :rent_id, :url
  belongs_to :document
  belongs_to :rent
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :nombre , :property_id
  belongs_to :property
end

app/models/surcharge.rb
class Surcharge < ActiveRecord::Base
  attr_accessible :folio, :invoice_id, :monto
  belongs_to :invoices
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name
  has_many :profiles,:dependent => :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :registerable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible  :url , :descripcion , :images_attributes
  has_many :images , :dependent => :destroy
  accepts_nested_attributes_for :images , 
  :reject_if => lambda { |a| a[:image_description].blank? } , 
  :allow_destroy => true
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titulo = "Home"
    @leases=Lease.where('status_renta'=> false)
    @message = Message.new
    @videos = Video.all
  end

  def show
        @lease = Lease.find(params[:id])
        respond_to do |format|
        format.html # mostrar.html.erb
        format.json { render json: @lease }
        format.js
      end 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def titulo
    base_titulo = "IPASA"
    if @titulo.nil?
      base_titulo
    else
      "#{base_titulo} | #{@titulo}"
    end
  end
  
  def logo
    logo = image_tag("logo.png", alt: "Sample App", class: "round")
  end

  def link_to_index_tab(controller)
    index_icon = '<i class="icon-th-list icon-white"></i> Lista'
    link_to raw(index_icon), {:controller => controller, :action => "index" , :format => :js}, :remote => true , 'data-toggle' => 'tab'
  end

  def link_to_new_tab(controller)
    new_icon = '<i class="icon-plus icon-white"></i> Agregar'
    link_to raw(new_icon), {:controller => controller, :action => "new" , :format => :js}, :remote => true , 'data-toggle' => 'tab'
  end

  def link_to_show(link)
    show_icon = '<i class="icon-th-list icon-white"></i>Mostrar'
    link_to raw(show_icon), link, {
      :remote => true, 'data-toggle' =>  "modal", 'data-target' => "#modal-window",
      'data-keyboard' => true, 'data-backdrop' => true, class: "btn btn-mini btn-success"
    }
  end

  def link_to_edit(link)
    edit_icon = '<i class="icon-pencil icon-white"></i>Editar'
    link_to raw(edit_icon), "#{link}/edit", {
      remote: true , 'data-toggle' =>  'modal', 'data-target' => '#modal-window', 
      'data-keyboard' => true, 'data-backdrop' => true, class: 'btn btn-mini btn-primary' 
    }
  end

  def link_to_delete(link)
    delete_icon = '<i class="icon-trash icon-white"></i>Eliminar'
    link_to raw(delete_icon), link , :method => :delete, confirm: 'Esta Seguro?', class: 'btn btn-mini btn-danger'
  end
end

app/views/layouts/admin/_footer.html.erb
<p>&copy; Company 2012</p>

app/views/layouts/admin/_lateralmenu.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">
      Administracion
    </li>
          <li class="<%= 'active' if params[:controller] == "admin/localities" %>"><%= link_to "Localidades", admin_localidades_path %></li>
  <li class="<%= 'active' if params[:controller] == "admin/properties" %>"><%= link_to "Propiedades", admin_propiedades_path %></li>
  <li class="<%= 'active' if params[:controller] == "admin/types" %>"><%= link_to "Tipos de inmuebles", admin_tiposinmueble_path %></li>
  <li class="<%= 'active' if params[:controller] == "admin/profiles" %>"><%= link_to "Perfiles de inmuebles", admin_perfiles_path %></li>

  <li class="<%= 'active' if params[:controller] == "admin/leases" %>"><%= link_to "Arrendamientos", admin_arrendamientos_path %></li>
  <li class="<%= 'active' if params[:controller] == "admin/videos" %>"><%= link_to "Videos", admin_Videos_path %></li>
  </ul>
</div>

app/views/layouts/admin/_navbar.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="brand" href="#">Sistema de administración IPASA</a>
			<%= render 'layouts/admin/userinfo'%>
		</div>
	</div>
</div>

app/views/layouts/admin/_userinfo.html.erb
<div class="btn-group pull-right">
	<a class="btn dropdown-toggle" data-toggle="dropdown">
		<i class="icon-user"></i> <%= current_user.email %>
		<span class="caret"></span>
	</a>
	<ul class="dropdown-menu">
	  <li><a href="#">Perfil</a></li>
	  <li class="divider"></li>
	  <li><%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete %></li>
	</ul>
</div>

app/views/layouts/admin/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= titulo %></title>
	  <%= csrf_meta_tags %>
	  <%= render "layouts/stylesheets"%>
	</head>
	<body class="admin">
		<%= render "layouts/admin/navbar" %>
		<div class="container">
			<div class="row">
				<div class="span3">
		  			<%= render 'layouts/admin/lateralmenu'%>
		  		</div>
			  	<div class="span9">
			  		<%= render 'shared/alerts'%>
			  		<%= render  "layouts/fancy" %>
					<section>
						<div >
							<%= yield %>
						</div>
					</section>
				</div>
			</div>
		</div>
			<footer>
				<%= render 'layouts/admin/footer'%>
				<%= debug(params) if Rails.env.development? %>
			</footer>
		<%= javascript_include_tag "application" %>
	</body>
</html>

app/views/shared/_alerts.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> fade in">
    	<%= value %>
    	<button type="button" class="close" data-dismiss="alert">×</button>
    </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>