config/routes.rb
Ipasa::Application.routes.draw do
  devise_for :users

  root :to => 'pages#home'
  resources :profiles
  resources :types
  resources :rents
  resources :lease_structures       
  resources :rent_documents
  resources :invoices
  resources :surcharges
  resources :documents  
  resources :duties  
  resources :leases
  resources :localities
  resources :properties
  resources :messages
  resources :pages
  
  namespace :admin do
    root :to => 'base#index'
      match "propiedades" , :to => "properties#tab"
      match "perfiles", :to => "profiles#tab"
      match "localidades", :to => "localities#tab"
      match "servicios", :to => "services#tab"
      match "tiposinmueble", :to => "types#tab"
      match "arrendamientos",:to => "leases#tab"
      match "Videos",:to=> "videos#tab"
      resources :properties
      resources :profiles
      resources :leases
      resources :localities
      resources :services
      resources :types
      resources :videos
  end
  match 'message'   => 'messages#new', :as => 'message', :via => :get
  match 'message'   => 'messages#create', :as => 'message', :via => :post
  
  

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible  :url , :descripcion , :images_attributes
  has_many :images , :dependent => :destroy
  accepts_nested_attributes_for :images , 
  :reject_if => lambda { |a| a[:image_description].blank? } , 
  :allow_destroy => true
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::ResourceController
  def index
    @videos = Video.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
      format.js
    end
  end

  def new
    @video = Video.new
    1.times { @video.images.build }
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
      format.js
    end
  end

  def edit
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @video }
      format.js
    end
  end

  def create
    @video = Video.new(params[:video])
    respond_to do |format|
      if @video.save
        format.html { redirect_to action:"tab" }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action:"new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @video = Video.find(params[:id])
    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to action:"tab" }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    respond_to do |format|
      format.html { redirect_to action:"tab" }
      format.json { head :no_content }
    end
  end

  def tab
    @videos = Video.all
     respond_to do |format|
      format.html
      format.js
    end
  end
end

app/views/admin/videos/_form.html.erb
<h1><%= @titulo %></h1>
<%= simple_form_for([:admin , @video], :html => { :class => 'form-horizontal' }) do |f| %>
<%= f.input :url %>
<%= f.input :descripcion %>
<%= f.simple_fields_for :images do |builder| %>
    <%= render :partial => 'image_fields', :locals => { :f => builder } %>
  <% end %>
    <%= f.button :submit %>
<% end %>

app/views/admin/videos/_image_fields.html.erb
<% unless f.object.new_record? %>
    <%= link_to image_tag(f.object.image.url(:thumb)) , f.object.image.url(:original) %>
    <%= f.input :image_description %>
    <%= f.input :_destroy, :as => :boolean %>
<% else %>
    <%= f.input :image %>
    <%= f.input :image_description %>
<%end%>

app/views/admin/videos/edit.html.erb
<%= render :partial => 'form' %>

app/views/admin/videos/edit.js.erb
$(document).ready(function() {
	$('.modal-body').empty();	
	$('.modal-body').html("<%= escape_javascript render :partial => 'form' %>");                   
});

app/views/admin/videos/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Url</th>
      <th>Fecha de subida</th>
      <th>Opciones</th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= link_to video.id, video_path(video) %></td>
        <td><%= video.url %></td>
        <td><%= video.created_at %></td>
        <td>
          <%= link_to_edit(admin_video_path(video)) %>
          <%= link_to_delete(admin_video_path(video)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/videos/index.js.erb
$(document).ready(function() {
    $('#content').html("<%= escape_javascript render(:file => 'admin/videos/index', :formats => [:html])  %>");
});

app/views/admin/videos/new.html.erb
<%= render :partial => 'form' %>

app/views/admin/videos/new.js.erb
$(document).ready(function() {
	$('#content').empty();
    $('#content').html("<%= escape_javascript render :partial => 'form' %>");
});

app/views/admin/videos/tab.html.erb
<ul class="nav nav-tabs">
	<li class="active"><%= link_to_index_tab("videos")%></li>
	<li><%= link_to_new_tab("videos")%></li>
</ul>
<div id="content" class="tab-pane active">
	<%= render(:file => 'admin/videos/index') %>
</div>